### PR TITLE
Conversion of Scripts to Python 3

### PR DESCRIPTION
**Pull request by HelgeCPH**
Hej Adam,

After a long time I was again reading your book _Your Code as a Crime Scene_. Thank you for it. It is really well written and inspiring.

Since I wanted to run some of your scripts and since Python 2 is close to EOL, I just thought you might be interested in my changes for Python 3. While doing that I fixed two minor issues [
4a552cc](https://github.com/adamtornhill/maat-scripts/commit/4a552cc24749f4266664f2e6df3fc5991e253c9d) and [359a3b5](https://github.com/adamtornhill/maat-scripts/commit/359a3b5003e296bd1a1e92873c63d436a8b8b48b).

Unfortunately, I do not know how to send a PR for a separate branch, as there are likely people who want to run the Python 2 scripts from the master branch. Please let me know if I should do anything different.

Best,
Helge

### CODE REVIEW

**Comment by adamtornhill** [comment]
Thanks a lot @HelgeCPH for your kind words, and thanks for the pull request!

I think we should provide two versions of the scripts: one for Python 2, and one version with your updated Python 3 scripts. We could either introduce a separate folder, e.g. `python3` that contains updated versions of all scripts. Or we could maintain a separate fork where we update the documentation to highlight that this is a Python 3 compatible version. We could then link from `maat-scripts` to the fork.

Which one would you prefer? I'm lending towards the fork.

**Comment by HelgeCPH** [comment]
Thank you for your reply and sorry for my late reply.

  > I think we should provide two versions of the scripts: one for Python 2, and one version with your updated Python 3 scripts. 

Yes, I agree. Likely many people use the Python 2 scripts as they are.

  > We could either introduce a separate folder, e.g. python3 that contains updated versions of all scripts. Or we could maintain a separate fork where we update the documentation to highlight that this is a Python 3 compatible version. We could then link from maat-scripts to the fork.
  >
  > Which one would you prefer? I'm lending towards the fork.

Let's do whatever suits you best. If it is the fork then we just do it as you suggested.

**Comment by Ryuno-Ki** [comment]
What's the status with this?

I picked up Software Design X-Rays which also refers to this project.

**Comment by wonderbird** [comment]
Hi @adamtornhill, @HelgeCPH and @Ryuno-Ki,

in https://github.com/wonderbird/maat-scripts I have combined @HelgeCPH's changes with the latest commit of @adamtornhill's master branch and resolved the conflicts shown below.

Next steps

- I suggest that you, @adamtornhill, create a branch "python3" in https://github.com/adamtornhill/maat-scripts
- Then I would create a pull request to that branch for https://github.com/wonderbird/maat-scripts
- Finally @HelgeCPH can close this pull request here

Best,
Stefan

**Comment by wonderbird** [comment]
P.S.: In addition I have [resolved a bug](https://github.com/wonderbird/maat-scripts/commit/c94755f345b52edc98ece9851a46bf51c4638b89) that surfaced with the python3 version of the merge_comp_freqs.py script.

**Comment by adamtornhill** [comment]
@wonderbird I have created the branch: https://github.com/adamtornhill/maat-scripts/tree/python3

We should also include a mention of the Python 3 support in the `README.md`.

**Comment by wonderbird** [comment]
Thanks @adamtornhill . I have created PR #11 with the intention to replace this PR.

**Comment by adamtornhill** [comment]
Closing this PR since the work was completed in #11.

**Pull request closed without merging**
